apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    role: backend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  selector:
    role: transport
  ports:
  - port: 5672
    targetPort: 5672
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: kubergroup
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-persistent
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      role: backend
  replicas: 1
  template:
    metadata:
      labels:
        role: backend
    spec:
      volumes:
      - name: photos
        persistentVolumeClaim:
          claimName: photos-persistent
      containers:
      - name: django
        image: photoregistry.azurecr.io/web:latest
        ports:
        - containerPort: 8000
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        volumeMounts:
        - name: photos
          mountPath: /media
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml
spec:
  selector:
    matchLabels:
      role: ml
  template:
    metadata:
      labels:
        role: ml
    spec:
      volumes:
      - name: photos
        persistentVolumeClaim:
          claimName: photos-persistent
      containers:
      - name: torch
        image: photoregistry.azurecr.io/ml:latest
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        volumeMounts:
        - name: photos
          mountPath: /media
        resources:
          requests:
            cpu: "500m"
            memory: "3Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transport
spec:
  selector:
    matchLabels:
      role: transport
  replicas: 1
  template:
    metadata:
      labels:
        role: transport
    spec:
      containers:
      - name: rabbit
        image: rabbitmq
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
