apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    role: backend
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  selector:
    role: transport
  ports:
  - port: 5672
    targetPort: 5672